# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 Klucznik MZ
THEME = {
    "name": "system",
    "bg_main": "palette(window)",
    "bg_panel": "palette(base)",
    "panel_bg": "palette(base)",
    "bg_panel_alt": "palette(base)",
    "dialog_bg": "palette(window)",
    "text": "palette(text)",
    "text_muted": "palette(mid)",
    "title": "#035C3E",
    "accent": "#035C3E",
    "accent_hover": "#04E38A",
    "accent_pressed": "palette(dark)",
    "button_bg": "palette(button)",
    "button_text": "#0B6B52",
    "button_hover": "palette(mid)",
    "button_pressed": "palette(dark)",
    "button_disabled_bg": "palette(button)",
    "button_disabled_text": "palette(mid)",
    "field_bg": "palette(base)",
    "field_alt_bg": "palette(base)",
    "selection_bg": "#035C3E",
    "selection_text": "#ffffff",
    "border": "palette(mid)",
    "hover": "rgba(4, 227, 138, 0.12)",
    "danger": "#d11a2a",
    "danger_hover": "rgba(209, 26, 42, 0.14)",
    "corner_bg": "rgba(0, 0, 0, 0.02)",
    "drop_bg": "qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 rgba(128, 128, 128, 0.2), stop:1 rgba(128, 128, 128, 0.05))",
    "drop_border": "1px solid palette(mid)",
    "drop_radius": "8px",
    "drop_color": "palette(text)",
    "icon_color": "palette(text)",
    "button_hover_text": "#0B6B52",
    "button_pressed_text": "palette(button-text)",
    "scrollbar_handle": "#035C3E",
    "scrollbar_handle_hover": "#04E38A",
}
